### ISSUE TITLE
Sample .env file?

### ISSUE THREAD

**Issue by GerritKuilder** [JoaoInez/apollify#19]
Hi,

trying to figure out 2 things
a) what is needed in the env file
b) the redirect URL after authentication

a sample env file might be helpful.

Kind Regards,

Gerrit Kuilder

**Comment by GerritKuilder** [comment]
OK, sofar I figured out:
CLIENT_ID=
CLIENT_SECRET=

REDIRECT_URI = http://server:port/profile
seems I am missing something as I am getting:

"Oops, seems you session has expired. Please login again."

repeatedly

**Comment by joaoinez** [comment]
Hey, in my local .env file I simply need to have this to have it work:

REDIRECT_URI=http://localhost:3000/profile
CLIENT_ID=your spotify client id

Maybe you're not setting your redirect URI correctly in your spotify developer dashboard?

**Comment by GerritKuilder** [comment]
Hello Jao,

my apologies, my setup was ok, the problem was in the chair... (PICNIC).
I fell for the mistake people make when they start with something new: blame the product rather than yourself. 

I  installed apolify also on my laptop, got the same message"Oops, seems you session has expired. Please login again.", even after refresh.
I checked with the dev tools in my browser:
api.spotify.com/v1/me/following?type=artist:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

It was a browser extension that I used, Privacy Badger blocked the access.

Whitelisting the page fixed everything.

Just what I needed, I am trying to create a 'Better Organized Spotify' but have an express based app now for my music I now try to add Nuxt-Vue in the mix too, which is very different with what I am used to. 
Went from static html, php/php frameworks etc to nodejs.  
Your app is quite an inspiration.

Thank you for your time.

Gerrit Kuilder
